target_parts:
  night: Ğ½Ğ¾Ñ‡ÑŒÑ
  morning: ÑƒÑ‚Ñ€Ğ¾Ğ¼
  day: Ğ´Ğ½Ñ‘Ğ¼
  evening: Ğ²ĞµÑ‡ĞµÑ€Ğ¾Ğ¼

target_conditions:
  drizzle: Ğ¼Ğ¾Ñ€Ğ¾ÑÑŒ ğŸŒ§ï¸
  light-rain: Ğ½ĞµĞ±Ğ¾Ğ»ÑŒÑˆĞ¾Ğ¹ Ğ´Ğ¾Ğ¶Ğ´ÑŒ ğŸŒ§ï¸
  rain: Ğ´Ğ¾Ğ¶Ğ´ÑŒ ğŸŒ§ï¸
  moderate-rain: ÑƒĞ¼ĞµÑ€ĞµĞ½Ğ½Ğ¾ ÑĞ¸Ğ»ÑŒĞ½Ñ‹Ğ¹ Ğ´Ğ¾Ğ¶Ğ´ÑŒ ğŸŒ§ï¸
  heavy-rain: ÑĞ¸Ğ»ÑŒĞ½Ñ‹Ğ¹ Ğ´Ğ¾Ğ¶Ğ´ÑŒ ğŸŒ§ï¸
  continuous-heavy-rain: Ğ´Ğ»Ğ¸Ñ‚ĞµĞ»ÑŒĞ½Ñ‹Ğ¹ ÑĞ¸Ğ»ÑŒĞ½Ñ‹Ğ¹ Ğ´Ğ¾Ğ¶Ğ´ÑŒ ğŸŒ§ï¸
  showers: Ğ»Ğ¸Ğ²ĞµĞ½ÑŒ ğŸŒ§ï¸
  wet-snow: Ğ´Ğ¾Ğ¶Ğ´ÑŒ ÑĞ¾ ÑĞ½ĞµĞ³Ğ¾Ğ¼ ğŸŒ§ï¸â˜ƒï¸
  light-snow: Ğ½ĞµĞ±Ğ¾Ğ»ÑŒÑˆĞ¾Ğ¹ ÑĞ½ĞµĞ³ â˜ƒ
  snow: ÑĞ½ĞµĞ³ â˜ƒ
  snow-showers: ÑĞ½ĞµĞ³Ğ¾Ğ¿Ğ°Ğ´ â˜ƒ
  hail: Ğ³Ñ€Ğ°Ğ´ ğŸŒ§ï¸
  thunderstorm: Ğ³Ñ€Ğ¾Ğ·Ğ° ğŸŒ©ï¸
  thunderstorm-with-rain: Ğ´Ğ¾Ğ¶Ğ´ÑŒ Ñ Ğ³Ñ€Ğ¾Ğ·Ğ¾Ğ¹ â›ˆï¸
  thunderstorm-with-hail: Ğ³Ñ€Ğ¾Ğ·Ğ° Ñ Ğ³Ñ€Ğ°Ğ´Ğ¾Ğ¼ â›ˆ
